languageCode = "zh-Hans"
baseURL = "https://pubean.com"
title = "æ‹é€—ç§‘æŠ€"
disqusShortname = "pubean"
googleAnalytics = "UA-99107869-1"

[[menu.main]]
  name = "é¦–é¡µ"
  weight = 10
  identifier = "home"
  url = "/"

[[menu.main]]
  name = "æœåŠ¡"
  weight = 20
  identifier = "service"
  url = "/service/"

[[menu.main]]
  name = "ä½œå“"
  weight = 30
  identifier = "works"
  url = "/works/"

[[menu.main]]
  name = "å…³äº"
  weight = 50
  identifier = "about"
  url = "/about/"

[taxonomies]
  tag = "tags"
  category = "category"

[params]
  author = "Ritchie Zhu"
  description = "è®©ä¸€åˆ‡æ›´åŠ æœ‰è¶£ ğŸ‰"
  keywords = "WEBå¼€å‘,å¼€æº,ç§»åŠ¨å¼€å‘,å¾®ä¿¡å¼€å‘,æœ‰è¶£"
  shortTitle = "Pubean Inc."
  themeColor = "#62c343"
  googleSiteVerification = "AXeY2RWl9scrD4FvQ6eL2jIXa89mNHUHalWwSr9N_bs"
  email = "hello@pubean.com"
  icp = "è‹ICPå¤‡16005986å·-1"
  paginate = 10
